#!/bin/bash

[ "$PWD" != "/engine" ] && echo "[FAILURE] Please Run From '/engine' Directory" && exit

video=${1-btTKApmxrtk}
stime=${2-000}
etime=${3-120}

cache=$(realpath cache)
tools=$(realpath tools)

SECONDS=0

echo -e "[ACQUIRE] ${video}: Starting"

if [ -s ${cache}/${video}.incoming.mp4 ]
then
    touch ${cache}/${video}.incoming.mp4

    echo -e "[ACQUIRE] ${video}: Skipping in ${SECONDS} Seconds\n"
else
    ${tools}/yt -q -f mp4 -o "${cache}/${video}.incoming.mp4" --write-sub --write-auto-sub --write-thumbnail ${video}

    echo -e "[ACQUIRE] ${video}: Finished in ${SECONDS} Seconds\n"
fi
