#!/bin/bash

[ "$PWD" != "/engine" ] && echo "[FAILURE] Please Run From '/engine' Directory" && exit

eval "$(conda shell.bash hook)" && setup="conda activate --no-stack" && ${setup} mp

video=${1-btTKApmxrtk}
stime=${2-000}
etime=${3-120}

cache=$(realpath cache)
tools=$(realpath tools)

SECONDS=0

echo [OVERLAY] ${video}: Starting

${tools}/mp/bazel-bin/actiq/predict_mp \
--calculator_graph_config_file=${tools}/overlay_mp.pbtxt \
--input_side_packets=input_sequence_example_path=${cache}/${video}.features.${stime}-${etime}.pb,input_video_path=${cache}/${video}.incoming.mp4,output_video_path=${cache}/${video}.outgoing.${stime}-${etime}.mp4,segment_size=5,overlap=4

echo [OVERLAY] ${video}: Finished in ${SECONDS} Seconds
